--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MlsDmitry/LangAPI
build-by-default: true
branches:
- master
projects:
  LangAPI:
    path: ""
    model: virion
    type: library
...
